#!/bin/bash

set -eu

if [ "$EUID" -ne 0 ]; then
  echo "Please run this script with sudo:"
  echo "sudo bash install_nopasswd.sh"
  exit 1
fi

USER_NAME=${SUDO_USER:-$USER}
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

RYZENADJ_BIN=""
for candidate in /usr/local/bin/ryzenadj /usr/bin/ryzenadj; do
  if [ -x "$candidate" ]; then
    RYZENADJ_BIN=$candidate
    break
  fi
done

# Enumerate explicit per-core sysfs paths. Never use a glob here: sudoers
# wildcards match '/' and '..', so a wildcarded tee rule would let any process
# running as $USER_NAME write arbitrary root-owned files (privilege escalation).
CPU_FREQ_RULES=""
CPU_GOV_RULES=""
for cpu_dir in /sys/devices/system/cpu/cpu[0-9]*; do
  CPU_FREQ_RULES="$CPU_FREQ_RULES, /usr/bin/tee $cpu_dir/cpufreq/scaling_max_freq"
  CPU_GOV_RULES="$CPU_GOV_RULES, /usr/bin/tee $cpu_dir/cpufreq/scaling_governor"
done
CPU_FREQ_RULES=${CPU_FREQ_RULES#, }
CPU_GOV_RULES=${CPU_GOV_RULES#, }

# Allow only the exact ryzenadj invocations the app makes (telemetry read plus
# the fixed presets from src/core/power.py), not free-form arguments.
RYZENADJ_RULES=""
if [ -n "$RYZENADJ_BIN" ]; then
  RYZENADJ_RULES="$RYZENADJ_BIN -i"
  while IFS= read -r preset_args; do
    RYZENADJ_RULES="$RYZENADJ_RULES, $RYZENADJ_BIN $preset_args"
  done < <(PYTHONPATH="$SCRIPT_DIR" python3 - <<'PY'
from src.core.power import PowerController

for preset in PowerController.POWER_PRESETS.values():
    print(
        f"--stapm-limit={preset['stapm']} --fast-limit={preset['fast']} "
        f"--slow-limit={preset['slow']} --tctl-temp={preset['tctl']}"
    )
PY
)
else
  echo "warning: ryzenadj not found; skipping ryzenadj sudo rules" >&2
fi

SUDOERS_TMP=$(mktemp)
trap 'rm -f "$SUDOERS_TMP"' EXIT

{
  echo "# Passwordless sudo rules for ROG Control (generated by install_nopasswd.sh)"
  echo "$USER_NAME ALL=(ALL) NOPASSWD: /usr/bin/true"
  echo "$USER_NAME ALL=(ALL) NOPASSWD: /usr/bin/install -d -m 0755 /etc/rog-control, /usr/bin/cat /etc/rog-control/profile.json, /usr/bin/tee /etc/rog-control/profile.json.tmp, /usr/bin/chmod 0644 /etc/rog-control/profile.json.tmp, /usr/bin/mv /etc/rog-control/profile.json.tmp /etc/rog-control/profile.json"
  echo "$USER_NAME ALL=(ALL) NOPASSWD: $CPU_FREQ_RULES"
  echo "$USER_NAME ALL=(ALL) NOPASSWD: $CPU_GOV_RULES"
  if [ -n "$RYZENADJ_RULES" ]; then
    echo "$USER_NAME ALL=(ALL) NOPASSWD: $RYZENADJ_RULES"
  fi
} > "$SUDOERS_TMP"

# A malformed sudoers.d file can lock sudo out entirely: validate first.
visudo -cf "$SUDOERS_TMP"

install -m 0440 "$SUDOERS_TMP" /etc/sudoers.d/rog-control

sed "s|@PROJECT_DIR@|$SCRIPT_DIR|g" "$SCRIPT_DIR/rog-control.service" > /etc/systemd/system/rog-control.service
chmod 0644 /etc/systemd/system/rog-control.service
systemctl daemon-reload
systemctl enable --now rog-control.service

echo "Successfully installed sudo rules for $USER_NAME."
echo "ROG Control can now save profiles, apply supported controls, and restore the saved profile after reboot."
echo "Note: re-run this script if you change the power presets or CPU core count."
